# name of the section 
# feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt
abuse_sh:
  - name: mine Abuse Recommended List
    miner: AbuseshTagsMiner
    args:
      cloud: recommended
    outputs:
      - resultPath: feeds/download/ipblocklist_recommended-ips.txt
azure:
  # each section contains a list of sources to fetch from
  # with specific details
  - name: mine Azure Public Cloud
    # the *miner* defines the source we are fetching from
    # see the action homepage for a list of supported sources
    # https://github.com/jtschichold/mm-cloud-services-miners
    # here we are fetching the list of Azure IP Ranges
    miner: AzureWithServiceTagsMiner
    # arguments to the miner, in this case the Azure Cloud we are
    # interested in
    args:
      cloud: PublicCloud
    # the result of the fetch is then saved in the locations specified
    # under outputs
    outputs:
      # the list of IP ranges is filtered using the default filter
      # and saved in feeds/public-cloud-ips.txt
      - resultPath: feeds/download/public-cloud-ips.txt
      # we add a second output here to save only the IPs
      # used by the service AzureAD
      - resultPath: feeds/download/public-cloud-azuread-ips.txt
        filter: "[?systemService=='AzureAD'].endpoint"
  # we add a second endpoint list, under the same section
  # this time we fetch the list of IPs of the Azure Germany Cloud
  - name: mine Azure Germany Cloud
    miner: AzureWithServiceTagsMiner
    args:
      cloud: GermanyCloud
    outputs:
      - resultPath: feeds/download/germany-cloud-ips.txt

o365:
  - name: mine O365
    miner: O365Miner
    args:
      instance: Worldwide
    outputs:
      - resultPath: feeds/download/o365-ips.txt
